# Generated by Django 5.1.2 on 2025-09-03 20:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_userprofile_team_jobtype_calendarevent_and_more'),
        ('cflows', '0002_update_foreign_keys_to_core'),
    ]

    operations = [
        # This migration is kept empty as the operations were moved to later migrations
        # to avoid conflicts. See 0004_add_workitem_enhancements and 0005_add_remaining_models
    ]
