# Generated by Django 5.2.6 on 2025-09-03 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_userprofile_team_jobtype_calendarevent_and_more'),
        ('cflows', '0003_auto_20250903_2057'),
    ]

    operations = [
        # Add enhanced fields to WorkItem
        migrations.AddField(
            model_name='workitem',
            name='rich_content',
            field=models.TextField(blank=True, help_text='Rich HTML content for detailed descriptions'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='priority',
            field=models.CharField(
                choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], 
                default='normal', 
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='workitem',
            name='tags',
            field=models.JSONField(default=list, help_text='List of tags for categorization'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workitem',
            name='estimated_duration',
            field=models.DurationField(blank=True, help_text='Estimated time to complete', null=True),
        ),
        
        # Add enhanced fields to Workflow
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_shared',
            field=models.BooleanField(default=False, help_text='Share with other organizations'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='auto_assign',
            field=models.BooleanField(default=False, help_text='Auto-assign work items to team members'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Workflow changes require approval'),
        ),
    ]
