# Generated by Django 5.2.6 on 2025-09-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0005_add_remaining_models'),
        ('core', '0002_organization_userprofile_team_jobtype_calendarevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (no spaces)', max_length=100)),
                ('label', models.CharField(help_text='Display label for users', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('checkbox', 'Checkbox'), ('select', 'Dropdown Select'), ('multiselect', 'Multiple Select'), ('email', 'Email'), ('url', 'URL'), ('phone', 'Phone Number')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, help_text='Default value (JSON for complex types)')),
                ('help_text', models.CharField(blank=True, help_text='Help text shown to users', max_length=500)),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=200)),
                ('min_length', models.PositiveIntegerField(blank=True, help_text='Minimum length for text fields', null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Maximum length for text fields', null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value for number fields', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value for number fields', max_digits=10, null=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select fields (JSON array)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('section', models.CharField(blank=True, help_text='Section to group fields', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.organization')),
                ('workflows', models.ManyToManyField(blank=True, help_text='Limit to specific workflows (empty = all workflows)', to='cflows.workflow')),
                ('workflow_steps', models.ManyToManyField(blank=True, help_text='Show only for specific steps', to='cflows.workflowstep')),
            ],
            options={
                'ordering': ['section', 'order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WorkItemCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cflows.customfield')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='cflows.workitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workitemcustomfieldvalue',
            unique_together={('work_item', 'custom_field')},
        ),
    ]
