# Generated by Django 5.2.6 on 2025-09-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_userprofile_team_jobtype_calendarevent_and_more'),
        ('cflows', '0006_auto_20250904_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemcustomfieldvalue',
            name='collected_by',
            field=models.ForeignKey(help_text='User who provided this data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='workitemcustomfieldvalue',
            name='workflow_step',
            field=models.ForeignKey(blank=True, help_text='Step where this data was collected', null=True, on_delete=django.db.models.deletion.CASCADE, to='cflows.workflowstep'),
        ),
    ]
