# Generated by Django 5.2.6 on 2025-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0007_add_custom_field_tracking'),
    ]

    operations = [
    ]
