# Generated by Django 5.2.6 on 2025-09-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_organization_type_and_more'),
        ('cflows', '0008_auto_20250905_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('teams', models.JSONField(blank=True, default=list)),
                ('job_types', models.JSONField(blank=True, default=list)),
                ('workflows', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=20)),
                ('booked_by', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_calendar_views', to='core.userprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='calendarview',
            unique_together={('user', 'name')},
        ),
    ]
