# Generated by Django 5.2.6 on 2025-09-05 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0009_add_calendarview'),
        ('core', '0001_initial'),
    ]

    operations = [
        # Add description field
        migrations.AddField(
            model_name='workflowtransition',
            name='description',
            field=models.TextField(blank=True, help_text="Detailed description of what this transition does"),
        ),
        
        # Add visual customization fields
        migrations.AddField(
            model_name='workflowtransition',
            name='color',
            field=models.CharField(
                choices=[
                    ('blue', 'Blue (Default)'),
                    ('green', 'Green (Success)'),
                    ('red', 'Red (Danger/Reject)'),
                    ('yellow', 'Yellow (Warning)'),
                    ('purple', 'Purple (Review)'),
                    ('indigo', 'Indigo (Process)'),
                    ('gray', 'Gray (Neutral)'),
                    ('orange', 'Orange (Alert)'),
                ],
                default='blue',
                help_text="Button color for this transition",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='icon',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'No Icon'),
                    ('fas fa-check', 'Checkmark (Approve)'),
                    ('fas fa-times', 'X Mark (Reject)'),
                    ('fas fa-arrow-right', 'Arrow Right (Next)'),
                    ('fas fa-undo', 'Undo (Return)'),
                    ('fas fa-eye', 'Eye (Review)'),
                    ('fas fa-edit', 'Edit (Modify)'),
                    ('fas fa-pause', 'Pause (Hold)'),
                    ('fas fa-play', 'Play (Start)'),
                    ('fas fa-stop', 'Stop (End)'),
                    ('fas fa-upload', 'Upload (Submit)'),
                    ('fas fa-download', 'Download (Retrieve)'),
                    ('fas fa-cog', 'Cog (Process)'),
                    ('fas fa-user', 'User (Assign)'),
                    ('fas fa-users', 'Users (Team)'),
                    ('fas fa-flag', 'Flag (Priority)'),
                    ('fas fa-clock', 'Clock (Schedule)'),
                    ('fas fa-star', 'Star (Favorite)'),
                    ('fas fa-thumbs-up', 'Thumbs Up'),
                    ('fas fa-thumbs-down', 'Thumbs Down'),
                ],
                help_text="Icon to display on the transition button",
                max_length=50,
            ),
        ),
        
        # Add behavioral options
        migrations.AddField(
            model_name='workflowtransition',
            name='requires_confirmation',
            field=models.BooleanField(default=False, help_text="Require user confirmation before executing this transition"),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='confirmation_message',
            field=models.CharField(blank=True, help_text="Custom confirmation message (if requires_confirmation is True)", max_length=200),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='auto_assign_to_step_team',
            field=models.BooleanField(default=False, help_text="Automatically assign work item to the destination step's assigned team"),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='requires_comment',
            field=models.BooleanField(default=False, help_text="Require a comment when using this transition"),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='comment_prompt',
            field=models.CharField(blank=True, help_text="Custom prompt for required comment", max_length=200),
        ),
        
        # Add permission and ordering fields
        migrations.AddField(
            model_name='workflowtransition',
            name='permission_level',
            field=models.CharField(
                choices=[
                    ('any', 'Any User'),
                    ('assignee', 'Current Assignee Only'),
                    ('team', 'Team Members Only'),
                    ('admin', 'Admin/Staff Only'),
                    ('creator', 'Creator Only'),
                    ('custom', 'Custom Conditions'),
                ],
                default='any',
                help_text="Who can use this transition",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='order',
            field=models.IntegerField(default=0, help_text="Display order for transition buttons"),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Whether this transition is available for use"),
        ),
        
        # Add timestamp fields
        migrations.AddField(
            model_name='workflowtransition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When this transition was created"),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text="When this transition was last updated"),
        ),
    ]
