# Generated by Django 5.2.6 on 2025-09-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration is part of a major architectural refactoring where core models
    (Organization, UserProfile, Team, JobType, CalendarEvent) are moved from the
    cflows app to the core app for better separation of concerns.
    
    Features implemented:
    - Centralized organization management in core app
    - Unified user profile system across all apps
    - Shared team and job type models for cross-app functionality
    - Enhanced calendar event system with better integration
    - Preparation for removing duplicate models from cflows
    """

    dependencies = [
        ('cflows', '0011_add_workflow_field_customization'),
        ('core', '0005_fix_empty_slugs'),
    ]

    operations = [
        # Remove unique_together constraints from models being moved to core
        # These constraints will be recreated in the core app
        migrations.AlterUniqueTogether(
            name='jobtype',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        
        # Remove foreign key fields that reference models being moved to core
        # These will be replaced with references to core models
        migrations.RemoveField(
            model_name='jobtype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        
        # Update foreign keys to point to core models
        # This enables workflows to work with centralized user management
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='created_workflows', 
                to='core.userprofile'
            ),
        ),
    ]