# Generated by Django 5.2.6 on 2025-09-06 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0011_add_workflow_field_customization'),
        ('core', '0005_fix_empty_slugs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobtype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to='core.userprofile'),
        ),
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['order', 'label']},
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cflows_bookings', to='core.team'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to='core.team'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='workitemhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='StepDataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_data_collections', to='core.userprofile')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_data_collections', to='cflows.workitem')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cflows.workflowstep')),
            ],
            options={
                'unique_together': {('work_item', 'workflow_step')},
            },
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
