# Generated by Django 5.2.6 on 2025-09-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cflows', '0012_alter_jobtype_unique_together_and_more'),
        ('core', '0008_alter_role_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepDataCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_data_collections', to='core.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='invitees',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='related_team',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='related_work_item',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'ordering': ['order', 'label']},
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_cflows_bookings', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='teambooking',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cflows_bookings', to='core.team'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to='core.team'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='workitemhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='stepdatacollection',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_data_collections', to='cflows.workitem'),
        ),
        migrations.AddField(
            model_name='stepdatacollection',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cflows.workflowstep'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.AlterUniqueTogether(
            name='stepdatacollection',
            unique_together={('work_item', 'workflow_step')},
        ),
    ]
