# Generated by Django 5.2.6 on 2025-09-08 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cflows", "0013_stepdatacollection_remove_calendarevent_created_by_and_more"),
        ("core", "0009_add_sub_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="allowed_edit_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teams that can edit this workflow and create work items",
                related_name="editable_workflows",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="allowed_view_teams",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teams that can view this workflow and its work items",
                related_name="viewable_workflows",
                to="core.team",
            ),
        ),
        migrations.AddField(
            model_name="workflow",
            name="owner_team",
            field=models.ForeignKey(
                blank=True,
                help_text="The team that owns and manages this workflow",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_workflows",
                to="core.team",
            ),
        ),
    ]
