version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-mediap}
      POSTGRES_USER: ${DB_USER:-mediap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    image: ghcr.io/liam-lillieroth/metatask:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
      GUNICORN_WORKERS: 4
      GUNICORN_TIMEOUT: 120
      COLLECT_STATIC: 1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  celery:
    image: ghcr.io/liam-lillieroth/metatask:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A mediap worker -l info
    volumes:
      - media_volume:/app/media

  celery-beat:
    image: ghcr.io/liam-lillieroth/metatask:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A mediap beat -l info

  caddy:
    image: caddy:2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - static_volume:/srv/staticfiles:ro
      - media_volume:/srv/media:ro

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  caddy_data: