# Generated by Django 5.2.6 on 2025-09-03 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_migrate_data_from_cflows"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal Account"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                    ("non_profit", "Non-Profit"),
                    ("educational", "Educational"),
                    ("government", "Government"),
                ],
                default="business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_create_organizations",
            field=models.BooleanField(
                default=False, help_text="Allow user to create new organizations"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["organization_type"], name="core_organi_organiz_58eb74_idx"
            ),
        ),
    ]
