# Generated by Django 5.2.6 on 2025-09-05 17:30

from django.db import migrations
from django.utils.text import slugify


def fix_empty_organization_slugs(apps, schema_editor):
    """Fix any organizations with empty slugs"""
    Organization = apps.get_model('core', 'Organization')
    
    for org in Organization.objects.filter(slug=''):
        base_slug = slugify(org.name)
        if not base_slug:  # If name contains only special characters
            base_slug = 'organization'
        
        # Ensure slug is unique
        slug = base_slug
        counter = 1
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        org.slug = slug
        org.save()


def reverse_fix_empty_organization_slugs(apps, schema_editor):
    """Reverse operation - not applicable"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_organization_type_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_empty_organization_slugs, reverse_fix_empty_organization_slugs),
    ]
