# Generated by Django 5.2.6 on 2025-09-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_is_organization_admin"),
        ("core", "0006_permission_role_rolepermission_role_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_roles",
                to="accounts.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="userroleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_roles",
                to="accounts.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userroleassignment",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="accounts.userprofile",
            ),
        ),
    ]
