# Generated by Django 5.2.6 on 2025-09-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_role_created_by_alter_role_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization'),
        ),
    ]
