# Generated by Django 5.2.6 on 2025-09-08 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_role_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='parent_team',
            field=models.ForeignKey(blank=True, help_text='Parent team - leave empty for top-level teams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teams', to='core.team'),
        ),
    ]
