# Generated by Django 5.2.6 on 2025-09-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_sub_teams'),
    ]

    operations = [
    ]
