# Generated by Django 5.2.6 on 2025-09-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auto_20250908_2029"),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroleassignment',
            name='assigned_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_roles',
                to='core.userprofile'
            ),
        ),
    ]
