# Generated by Django 5.2.6 on 2025-09-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20250909_2048"),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the old constraint pointing to accounts_userprofile
            "ALTER TABLE core_userroleassignment DROP CONSTRAINT IF EXISTS core_userroleassignm_user_profile_id_2a2122ee_fk_accounts_;",
            # Reverse SQL (recreate the old constraint if rolling back)
            "ALTER TABLE core_userroleassignment ADD CONSTRAINT core_userroleassignm_user_profile_id_2a2122ee_fk_accounts_ FOREIGN KEY (user_profile_id) REFERENCES accounts_userprofile(id) DEFERRABLE INITIALLY DEFERRED;"
        ),
        migrations.RunSQL(
            # Add the correct constraint pointing to core_userprofile
            "ALTER TABLE core_userroleassignment ADD CONSTRAINT core_userroleassignm_user_profile_id_2a2122ee_fk_core_user FOREIGN KEY (user_profile_id) REFERENCES core_userprofile(id) DEFERRABLE INITIALLY DEFERRED;",
            # Reverse SQL (drop the new constraint if rolling back)
            "ALTER TABLE core_userroleassignment DROP CONSTRAINT IF EXISTS core_userroleassignm_user_profile_id_2a2122ee_fk_core_user;"
        )
    ]
