# Generated by Django 5.2.6 on 2025-09-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_userroleassignment_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroleassignment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.userprofile'),
        ),
    ]
