# Generated by Django 5.2.6 on 2025-09-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='service',
            field=models.CharField(blank=True, help_text="Service this role applies to (e.g., 'cflows', 'scheduling')", max_length=100),
        ),
    ]
