# Generated by Django 5.2.6 on 2025-09-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userrole_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_organization_admin",
            field=models.BooleanField(default=False),
        ),
    ]
