# Generated by Django 5.2.6 on 2025-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_is_organization_admin'),
        ('core', '0008_alter_role_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='organizationmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='user',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('metatask_support', 'MetaTask Support'), ('metatask_admin', 'MetaTask Admin'), ('metatask_moderator', 'MetaTask Moderator'), ('metatask_editor', 'MetaTask Editor'), ('workflow_manager', 'Workflow Manager'), ('process_designer', 'Process Designer'), ('job_planner', 'Job Planner'), ('resource_manager', 'Resource Manager'), ('team_leader', 'Team Leader'), ('standard_user', 'Standard User')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
