# Generated by Django 5.2.5 on 2025-09-02 18:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'Custom')], max_length=50)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='Maximum users allowed, null for unlimited', null=True)),
                ('max_projects', models.PositiveIntegerField(blank=True, help_text='Maximum projects allowed, null for unlimited', null=True)),
                ('max_storage_gb', models.PositiveIntegerField(blank=True, help_text='Maximum storage in GB, null for unlimited', null=True)),
                ('features', models.JSONField(default=list, help_text='List of included features')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='CSS class or icon identifier', max_length=100)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('current_users', models.PositiveIntegerField(default=0)),
                ('current_projects', models.PositiveIntegerField(default=0)),
                ('current_storage_gb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_billing_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.organization')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.licensetype')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.PositiveIntegerField()),
                ('projects_count', models.PositiveIntegerField()),
                ('storage_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('api_calls', models.PositiveIntegerField(default=0)),
                ('active_sessions', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='licensing.license')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='licensetype',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_types', to='licensing.service'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'status'], name='licensing_l_organiz_945a93_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['end_date'], name='licensing_l_end_dat_6d239d_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseusagelog',
            index=models.Index(fields=['license', 'recorded_at'], name='licensing_l_license_84c037_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='licensetype',
            unique_together={('service', 'name')},
        ),
    ]
