# Generated by Django 5.2.6 on 2025-09-03 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_organization_organization_type_and_more"),
        ("licensing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("personal", "Personal Account"),
                    ("organization", "Organization Account"),
                ],
                default="organization",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="api_calls_reset_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="license",
            name="current_api_calls_today",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="license",
            name="current_workflows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="license",
            name="is_personal_free",
            field=models.BooleanField(
                default=False, help_text="Is this a personal free account"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licensetype",
            name="display_name",
            field=models.CharField(
                default="Standard License",
                help_text="User-friendly name",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="licensetype",
            name="is_personal_only",
            field=models.BooleanField(
                default=False, help_text="Available only for personal accounts"
            ),
        ),
        migrations.AddField(
            model_name="licensetype",
            name="max_api_calls_per_day",
            field=models.PositiveIntegerField(
                blank=True, help_text="API rate limits", null=True
            ),
        ),
        migrations.AddField(
            model_name="licensetype",
            name="max_workflows",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum workflows allowed, null for unlimited",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="licensetype",
            name="requires_organization",
            field=models.BooleanField(
                default=False, help_text="Requires organization membership"
            ),
        ),
        migrations.AddField(
            model_name="licensetype",
            name="restrictions",
            field=models.JSONField(default=list, help_text="List of restrictions"),
        ),
        migrations.AddField(
            model_name="service",
            name="allows_personal_free",
            field=models.BooleanField(
                default=True, help_text="Allow free personal use"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="personal_free_limits",
            field=models.JSONField(
                default=dict, help_text="Limits for personal free accounts"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending"),
                    ("trial", "Trial"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("personal_free", "Personal Free"),
                    ("basic", "Basic"),
                    ("professional", "Professional"),
                    ("enterprise", "Enterprise"),
                    ("custom", "Custom"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="license",
            unique_together={("organization", "license_type")},
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["account_type", "is_personal_free"],
                name="licensing_l_account_394fef_idx",
            ),
        ),
    ]
