# Generated by Django 5.2.6 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_license_account_type_license_api_calls_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal Account'), ('organization', 'Organization Account'), ('customer-service', 'Customer Service Account')], default='organization', max_length=20),
        ),
    ]
