# Generated by Django 5.2.6 on 2025-09-10 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_role_created_by'),
        ('licensing', '0003_alter_license_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom license name', max_length=200)),
                ('max_users', models.PositiveIntegerField(help_text='Maximum number of users allowed')),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for unlimited duration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('included_features', models.JSONField(default=list, help_text='List of included features')),
                ('restrictions', models.JSONField(default=dict, help_text='Custom restrictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for customer support')),
                ('created_by', models.ForeignKey(help_text='Customer support user who created this', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_licenses', to='core.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_licenses', to='licensing.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='custom_license',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_instance', to='licensing.customlicense'),
        ),
        migrations.CreateModel(
            name='UserLicenseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_licenses', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='licensing.license')),
                ('revoked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_licenses', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'License Created'), ('assign', 'User Assigned'), ('revoke', 'User Revoked'), ('modify', 'License Modified'), ('expire', 'License Expired'), ('extend', 'License Extended'), ('suspend', 'License Suspended'), ('reactivate', 'License Reactivated')], max_length=20)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('custom_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licensing.customlicense')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licensing.license')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licensing.userlicenseassignment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='customlicense',
            index=models.Index(fields=['organization', 'service', 'is_active'], name='licensing_c_organiz_f576d7_idx'),
        ),
        migrations.AddIndex(
            model_name='customlicense',
            index=models.Index(fields=['end_date'], name='licensing_c_end_dat_c31ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='userlicenseassignment',
            index=models.Index(fields=['license', 'is_active'], name='licensing_u_license_699687_idx'),
        ),
        migrations.AddIndex(
            model_name='userlicenseassignment',
            index=models.Index(fields=['user_profile', 'is_active'], name='licensing_u_user_pr_d4bf6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlicenseassignment',
            unique_together={('license', 'user_profile')},
        ),
        migrations.AddIndex(
            model_name='licenseauditlog',
            index=models.Index(fields=['license', 'timestamp'], name='licensing_l_license_06e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseauditlog',
            index=models.Index(fields=['custom_license', 'timestamp'], name='licensing_l_custom__851903_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseauditlog',
            index=models.Index(fields=['performed_by', 'timestamp'], name='licensing_l_perform_9d5924_idx'),
        ),
    ]
